# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: imperfect perfectionist
#email: calliope1226@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  딥러닝을 잘 모르는 인공지능 연구원입니다. 이것저것 잡다하게 좋아하고, 블로그에 기록하려고 노력하고 있습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dreamingjudith.github.io" # the base hostname & protocol for your site
github_username:  dreamingjudith
disqus: dreamingjudith

# Build settings
markdown: kramdown
